# Generated by Django 4.2.7 on 2023-11-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='project_tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_images',
        ),
        migrations.AddField(
            model_name='project',
            name='project_images',
            field=models.ManyToManyField(to='app_personal_website.projectimage'),
        ),
    ]
