# Generated by Django 5.0 on 2024-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal_website', '0002_projectimage_remove_project_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='at_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
